Header
IvanPlastun/webdev-team02 pull request #11
Opened 2018-12-03 14:38 UTC by iiMikhail

Header complete.

2018-12-03 15:41 UTC, nobleworkshop requested changes
1) Т.к. лого используется один, то надо вынести его в отдельную секцию или миксин и подключать его оттуда.
2) Разница миксина от секции, в том что миксин предусматривает параметры которые они принимает при вызове. В данном случае миксин header-user-block стоит переделать в секцию.

2018-12-03 19:15 UTC, iiMikhail commented
Изменения внес и закомитил. Логотип теперь выделен в качестве секции.
@nobleworkshop, @IvanPlastun  прошу проверить и дать добро на мерж.

2018-12-04 10:13 UTC, IvanPlastun requested changes
Необходимо поправить отступы т.к. высота header не соответствует высоте на макете, а на макете высота блока header равна 200px.

2018-12-04 10:13 UTC, IvanPlastun commented on src/less/sections/_header.less
>  	margin-bottom: 20px;
Отступ между header__wrapper и навигацией равен 36px, необходимо поправить.

2018-12-04 10:13 UTC, IvanPlastun commented on src/pug/pages/ui/header-guest.pug
> +						.logo__description--first Digital Lifestyle
Отступ снизу между данным блоком и блоком с классом .logo__description--second равен 20px.

2018-12-04 10:20 UTC, IvanPlastun requested changes
Внести изменения.

2018-12-04 10:20 UTC, IvanPlastun commented on src/pug/pages/ui/header-guest.pug
> +						.logo__img
Для чего нужен элемент .logo__img, если картинка для логотипа задается через псевдокласс? Необходимо его убрать.

2018-12-04 10:52 UTC, IvanPlastun commented
Изменить стили для кнопок у шапки пользователя, добавить эффекты по наведению и нажатию. Или использовать кнопки из миксина с кнопками и немного переопределить их стили с помощью класса модификатора для шапки. Например, `+button('Профиль', '#', 'profile')(class="свой класс модификатор")`

2018-12-04 12:37 UTC, iiMikhail commented
Ошибки пофиксил.
@IvanPlastun , @nobleworkshop, просьба проверить

2018-12-04 13:24 UTC, IvanPlastun requested changes
Внести изменения.

2018-12-04 13:24 UTC, IvanPlastun commented on src/less/blocks/_logo.less
>  .logo__description--second {
Элементы не могут быть модификаторами заменить например на logo__description и для .logo__description--first тоже заменить, например на logo__title

2018-12-04 17:45 UTC, iiMikhail commented
Модификаторы заменены на элементы.

2018-12-05 09:44 UTC, IvanPlastun commented
Необходимо внести изменения:
1) Убрать свойство `margin-bottom: 10px` у элемента nav.
2) Изменить расстояние между ссылками `Войти` и `Зарегистрироваться` на шапке guest на 30px
3) Изменить `div.header` на тег html5 `header.header`
4) Изменить отступы между элементами ссылок в блоке `nav` на 50px
5) Удалить лишние миксины для ссылок, которые используются в шапке. Использовать один миксин для них, т.к. они одинаковы по стилизиации и функциональности
6)Изменить отступ между навигацией и логотипом на 35px
7) Изменить отступ между аватаркой и блоком с именем и кнопками в правом углу блока header-пользователь на 16px
8) В блоке в правом верхнем углу блока header-пользователь изменить расстояние между кнопками на 10px

2018-12-09 13:37 UTC, iiMikhail commented
Внес новый коммит. Доработал правки + сделал лого вектором
@IvanPlastun , @nobleworkshop  прошу проверить и дать обратную связь

2018-12-09 14:35 UTC, IvanPlastun requested changes
1) В CSS стилях классу .svg-inline--fa установить отступ справа margin-right: 0 !important;
2) В блоке в правом верхнем углу header-пользователь изменить расстояние между кнопками на 10px

2018-12-09 14:40 UTC, iiMikhail commented
complete

2018-12-09 15:02 UTC, IvanPlastun approved these changes
Все хорошо, но у  элемента с классом `logo__description` необходимо увеличить margin-left с 41px до `42px`. После этого устраняй конфликты и выполняй слияние.

2018-12-09 16:07 UTC, merged