Admin header
IvanPlastun/webdev-team02 pull request #12
Opened 2018-12-03 16:24 UTC by chl9252

Шапка администратора на первую проверку (ветка admin-header)

2018-12-04 11:30 UTC, IvanPlastun requested changes
Необходимо внести изменения.

2018-12-04 11:30 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +	margin-left: 30px;
Удалить отступ у первого элемента ссылки используя псевдокласс :first-child т.к. отступ получается между блоком с именем и бейджем не 40px, а 70px.

2018-12-04 11:30 UTC, IvanPlastun commented on src/pug/pages/ui/header-admin.pug
> +								p.mt-0.mb-0 Юрий Ключевский
Добавить стилизацию для данного параграфа с именем не соответствует дизайну. Задать для него класс и прописать стили, допустим brif__name. Удалить утилитарные классы mt-0.mb-0 задать сброс отступов при стилизации. Удалить свойство line-height: 2 и добавить padding-bottom параграфу для отступа снизу от бейджа.

2018-12-04 11:30 UTC, IvanPlastun commented on src/pug/pages/ui/header-admin.pug
> +						.user.ml-15
Отступ слева от этого блока должен быть 20px, а не 15.

2018-12-04 11:30 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +/*	width: 1600px;*/
Удалить закоментированное свойство.

2018-12-04 11:30 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +	justify-content: flex-start;
данное свойство можно удалить т.к. блоки уже спозиционированны и прижаты к началу блока свойство `justify-content: space-between;` У блока header-admin.

2018-12-04 11:30 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +	justify-content: flex-start;
Здесь тоже следует убрать данное свойство т.к. элементы уже прижаты к левому краю блока.

2018-12-04 14:06 UTC, chl9252 commented
Исправила 6 пунктов.

2018-12-04 16:58 UTC, IvanPlastun requested changes
Необходимы изменения.

2018-12-04 16:58 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +	padding-bottom: 10px;
Убрать отступ padding-bottom: 10px; У данной секции он тут не нужен по дизайну блок с именем и бейджем лежит чуть-чуть ниже аватара.

2018-12-04 16:58 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +	& p {
Убрать данный селектор по тегу т.к. у вас имеется класс .brif__name в нем можно выполнять стилизацию имени.

2018-12-04 16:58 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +.brif__name {
Добавить этому классу следующий код:
`margin: 0;
 margin-bottom: 6px;`
Для того чтобы сбросить отступы параграфа и добавить отступ от него и до бейджа в 6px.

2018-12-04 16:58 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
>  	font-family: @boldFont;
Изменить значение свойства на  `font-family: @baseFont;` Удалить переменную @boldFont. `Exstrabold` - это начертание шрифта, это значение для свойства font-weight. Значение свойства `font-weight` в начертании Exstrabold 800. Замените font-weight на 800, а не 400. 400 - это regular.

2018-12-04 16:58 UTC, IvanPlastun commented on src/pug/pages/ui/header-admin.pug
> +						.admin-nav.ml-70
Данный отступ по дизайну должен быть 50px, а не 70px. Я же писал) "Удалить отступ у первого элемента ссылки используя псевдокласс :first-child т.к. отступ получается между блоком с именем и бейджем не 50px, а 70px." Если бы вы отступ не убрали у первого элемента навигации с помощью псевдокласса :first-child, то у вас бы вместе с этим отступом от первого пункта меню в 30px + 40px = 70px, которые у вас были, то получался отступ больше чам 40px, но по дизайну между этим блоком и блоком с именем и бейджем должен быть оступ в `50px`. Установите его в 50px, 70 удалите.  Я писал 40px, немного ошибся, посмотрел ещё раз шапку между этими блоками 50px.

2018-12-04 19:15 UTC, chl9252 commented
Исправила.
Вот только параграф (с именем администратора) не хочет стилизоваться по имени класса, только по тегу. Проба стилизовать по имени класса:
[https://drive.google.com/open?id=12QNTpFpKpz5nr3QneyWAokvttEJLmK83](url)

2018-12-05 08:18 UTC, chl9252 commented
Исправила.
Вот только параграф (с именем администратора) не хочет стилизоваться по имени класса, только по тегу. Проба стилизовать по имени класса:
[https://drive.google.com/open?id=12QNTpFpKpz5nr3QneyWAokvttEJLmK83](url)

2018-12-05 08:30 UTC, chl9252 commented
>           Исправила.
> Вот только параграф (с именем администратора) не хочет стилизоваться по имени класса, только по тегу. Проба стилизовать по имени класса:
> скриншот в карточке

2018-12-05 10:22 UTC, IvanPlastun requested changes
А так уже ошибок больше нет.
Необходимо внести изменения:
1) Изменить `.admin-nav` на `nav.admin-nav`. nav это семантический тег html5, который используется для навигации, а когда задаем просто `.admin-nav`, то создается блок div.
2) Обернуть миксин с аватаркой в ссылку вот таким образом:
`a(class="avatar-link" href="#")
	+avatar('avatar.jpg', 'alt text avatar', 'small')`
Ссылке к классу `avatar-link` прописать свойство `display: block;` т.к. блочные элементы нельзя вкладывать в строчные, поэтому ссылка должна быть блоком.
3) Удалить свойство `margin-right` у ссылки находящейся внутри блока с классом `header-admin__right` и добавить отступ справа к этому блоку. Вот так:
`.header-admin__right { 
       margin-right: 50px;
}`

2018-12-05 10:22 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +	& p {
Стилизацию по тегу можно оставить, если стили не переопределяются.

2018-12-05 12:59 UTC, chl9252 commented
Исправила

2018-12-05 17:18 UTC, IvanPlastun commented
.header-admin__right
 	a(href="#!")
 		i.fas.fa-sign-out-alt - расстояние между этой иконкой и текстом `Выход должно быть 8px` 8px потому что там уже есть небольшой отступ между ними. По дизайну посмотрите есть небольшой отступ между иконкой и текстом.
 		|  Выход

2018-12-05 21:06 UTC, chl9252 commented
Исправила

2018-12-06 08:27 UTC, IvanPlastun requested changes
Внести изменения.

2018-12-06 08:27 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +
Все хорошо, но зачем два селектора для свойств `font-size` и `margin-right` оставьте какой-нибудь один. После того как удалите один из этих селекторов, устраняйте конфликты, если они есть и выполняйте слияние в develop. Потому что один из селекторов перекрывает другой, оставьте только один, который задаст размер шрифта и внешний отступ справа.

2018-12-06 08:36 UTC, chl9252 commented on src/less/sections/_header-admin.less
> +
margin-right разный. У "выхода" больше.  Или они равны?

2018-12-06 09:09 UTC, IvanPlastun requested changes

2018-12-06 09:09 UTC, IvanPlastun commented on src/less/sections/_header-admin.less
> +
@chl9252, нужно оставить либо вот этот код
`.svg-inline--fa {
	margin-right: 8px;
	font-size: 18px;
}` // но лучше я думаю оставить вот этот стиль.
Либо вот этот
`.fa-sign-out-alt { // а вот этот удалить.
	margin-right: 11px; 
	font-size: 18px;	
}`
Потому что работает только один селектор, это одинаковые стили с разницей в отступах, посмотрите в инспекторе. Одни стили не активны, а другие активны.

2018-12-06 11:52 UTC, IvanPlastun approved these changes
Все хорошо, устраняйте конфликты, если они есть и выполняйте мердж в develop.

2018-12-06 12:31 UTC, merged