Cards
IvanPlastun/webdev-team02 pull request #18
Opened 2018-12-04 14:10 UTC by sanata713

2018-12-04 18:29 UTC, IvanPlastun requested changes
Необходимо внести изменения.

2018-12-04 18:29 UTC, IvanPlastun commented on src/pug/mixins/_cards.pug
> +        .card__plate
Неверно. У нас в проекте есть BEM-naming, который использует блок, элемент, модификатор. У вас же задан класс ` .card__plate`, элемент существует сам по себе, но такого быть не должно. `! Элемент не может существовать без блока`.  Сделайте карточке класс `.card` или `card-box`, который будет являться блоком. Внутри него размещайте другие элементы элементы добавляются к блокам с помощью `__`, например:
`.card
    .card__image
         блок с изображением карточки
    .card__title Заголовок карточки`

2018-12-04 18:29 UTC, IvanPlastun commented on src/pug/mixins/_cards.pug
> +        .card__plate
Тут аналогично изменить `.card__plate`, снова элемент сам по себе, создайте для него блок.

2018-12-04 18:29 UTC, IvanPlastun commented on src/less/blocks/_cards.less
> +    overflow: hidden;
Убрать свойство `overflow: hidden;`, т.к. часть небольшая часть заголовка скрывается за пределами блока.

2018-12-05 11:11 UTC, IvanPlastun requested changes
Необходимо внести изменения.

2018-12-05 11:11 UTC, IvanPlastun commented on src/less/blocks/_cards.less
> +.card-box {
1) Оставить какой-нибудь один класс `.card-box` или `.card`
2) Удалить свойство 'flex-direction: column;' оно тут не требуется, т.к. у вас в карточке все элементы являются блоками и уже переносятся корректно на новую строку.

2018-12-05 11:11 UTC, IvanPlastun commented on src/less/blocks/_cards.less
>  }
Удалить данный селектор.

2018-12-05 11:11 UTC, IvanPlastun commented on src/less/blocks/_cards.less
>  }
У данного блока не следует задавать высоту, пусть его высота будет равна высоте содержимого. Добавить в данный селектор свойство `word-break: break-word; `, чтобы текст всегда корректно переносился на новую строку.

2018-12-05 11:17 UTC, sanata713 commented on src/less/blocks/_cards.less
> +.card-box {
Это из-за множества коммитов такое произошло, скорей всего. Я везде убирала _card__plate и заменила его на card-box. У меняя в коде на компе этого класса нет. Может мне заново попробовать отправить на гитхаб?

2018-12-05 11:18 UTC, sanata713 commented on src/less/blocks/_cards.less
>  }
Этот селектор я не могу удалить, потому что на него ссылается вот эта страница 
![image](https://user-images.githubusercontent.com/44693552/49510233-69069280-f8a9-11e8-9fe0-77822828b6c0.png)

2018-12-05 11:19 UTC, sanata713 commented on src/less/blocks/_cards.less
>  }
И то убирала, не знаю, почему код некорректно ушел на репозиторий. Свойство добавлю сейчас.

2018-12-05 11:35 UTC, sanata713 commented on src/less/blocks/_cards.less
> +.card-box {
Всё поправила. Проверила, сейчас такого нет.

2018-12-05 11:35 UTC, sanata713 commented on src/less/blocks/_cards.less
>  }
Поправила.

2018-12-05 12:42 UTC, IvanPlastun commented on src/less/blocks/_cards.less
> +.card-box {
Нет, не .card__plate он удален видите он красный. Вам надо удалить один из классов .card или .card-box Чтобы остался только один из них, а не оба.

2018-12-05 12:43 UTC, IvanPlastun commented on src/less/blocks/_cards.less
>  }
В смысле как? Главная страница сайта может ссылаться на селектор расположенный в файле стилей с карточками?

2018-12-05 12:46 UTC, IvanPlastun requested changes
Высота должна зависеть от содержимого.

2018-12-05 12:46 UTC, IvanPlastun commented on src/less/blocks/_cards.less
>      height: 50px;
Высоту необходимо убрать.

2018-12-05 12:47 UTC, sanata713 commented on src/less/blocks/_cards.less
>  }
_card.less не я создавала, он уже был

2018-12-05 12:47 UTC, sanata713 commented on src/less/blocks/_cards.less
>  }
Я не стала создавать новый файл в less поэтому

2018-12-05 12:47 UTC, IvanPlastun commented on src/less/blocks/_cards.less
>  }
Вам нужно удалить вот этот селектор `.card-box { display: flex;}`

2018-12-05 12:48 UTC, sanata713 commented on src/less/blocks/_cards.less
>      height: 50px;
А если будет заголовок из одной строки, тогда карточка будет меньше по высоте?

2018-12-05 12:49 UTC, sanata713 commented on src/less/blocks/_cards.less
>  }
такого селектора и нет

2018-12-05 13:42 UTC, IvanPlastun commented on src/less/blocks/_cards.less
>      height: 50px;
Применить следующие стили для блока `
`.card-box {
    width: 360px;
    height: 308px;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
}`

а кнопке добавить класс модификатор со значением
`align-self: flex-start;`
У кнопок предусмотрена возможность добавления дополнительных атрибутов и их значений. 
Создать класс модификатор для высоты карточки т.к. высота карточки в portfolio отличается от высоты карточки для поста в блоге. Например: `.card-box--height`

2018-12-05 18:20 UTC, IvanPlastun approved these changes
Все хорошо) Можете выполнять слияние в develop устранив конфликты, если они есть. Перед слиянием обязательно перейдите в ветку develop и выполните команду `git pull`, чтобы подгрузить актуальную версию ветки. После перейдите в ветку cards и выполните команду `git merge develop`, если возникнут конфликты устраните и закомитьте их и после командой `git push origin cards` отправьте ветку в удаленный репозиторий и выполните слияние в develop.

2018-12-06 04:46 UTC, merged