footer ready
IvanPlastun/webdev-team02 pull request #19
Opened 2018-12-05 16:03 UTC by EvgeniyaRo

Футер до правок.

2018-12-05 17:54 UTC, IvanPlastun requested changes
Необходимы изменения.

2018-12-05 17:54 UTC, IvanPlastun commented on src/less/sections/_footer.less
> +	padding: 0 0 25px 0;
Удалить вот этот отступ `padding: 0 0 25px 0;` и вместо него параграфу установить отступ `margin-bottom: 20px`. И с помощью
`.footer__container p:last-child {
      margin-bottom: 0; //Сбросить отступ у последнего параграфа.
}`

2018-12-05 17:54 UTC, IvanPlastun commented on src/pug/pages/ui/footer.pug
> +
`.col-2.offset-1
       .footer__nav
		a(href="#!") Главная
		a(href="#!") Обо мне
		a(href="#!") Работы
		a(href="#!") Блог
		a(href="#!") Контакты`
Вот так вот должно быть, навигация должна лежать внутри колонки, а не являться колонкой.
Заменить  .footer__nav на `nav.footer__nav`. nav - это семантический тег html5 используемый для навигации.

2018-12-05 17:54 UTC, IvanPlastun commented on src/pug/pages/ui/footer.pug
> +								a(href="#!") Контакты
У данной ссылки с помощью псевдокласса: 
`.footer__nav a:last-child {
        margin-bottom: 0;  //Установить отступ снизу 0
}` 
Так же для ссылок добавить эффект при наведении `:hover` Чтобы появлялось подчеркивание.
Вот так:
`.footer__nav a:hover { 
     text-decoration: underline;
}`

2018-12-05 17:54 UTC, IvanPlastun commented on src/pug/pages/ui/footer.pug
> +
Я немного ошибся в описании к карточке с блоком footer переделайте немного классы сетки, поскольку сетка занимает `12 колонок`, а не 10. Сделайте для первого блока, в котором лежит copyright `col-5`, для второго блока `col-3` и удалите `offset-1`, а для последнего блока с элементами социальных иконок установите `col-4`. И сделайте чтобы контент лежал внутри колонок. Вот так:
`.col-4.offset-1
     .social
	    +icon-font('https://www.youtube.com/?gl=RU&hl=ru', 'fab fa-vk')
	    +icon-font('https://www.youtube.com/?gl=RU&hl=ru', 'fab fa-twitter')
	    +icon-font('https://www.youtube.com/?gl=RU&hl=ru', 'fab fa-youtube')
	    +icon-font('https://www.youtube.com/?gl=RU&hl=ru', 'fab fa-instagram')
	    +icon-font('https://www.youtube.com/?gl=RU&hl=ru', 'fab fa-facebook-f')`
Это для примера, остальные колонки должны быть сделаны аналогично.

2018-12-05 17:54 UTC, IvanPlastun commented on src/pug/pages/ui/footer.pug
> +
Элементам ссылкам с социальными иконками не нужно задавать адреса в атрибуте `href`, необходимо установить его значение `href = #!`. Также для них необходимо добавить эффект при наведении в дизайне он желтого цвета и добавить  LESS миксин `.transition` для плавности к ссылке.
Убрать отступ `margin-right: 35px` у элемента `span` c классом `social-icon` и добавить его к ссылке равным `40px потому что по дизайну расстояние между ссылками с социальными иконками 40px, а не 35px как у вас установлено`, все стили добавить к ссылке и размер шрифта, цвет текста. К иконкам стили задавать не нужно, иконки будут наследовать стили от ссылок. 
У последнего элемента ссылки с социальной иконкой с помощью псевдокласса `:last-child` сбросить отступ справа установив его `margin-right: 0`.

2018-12-05 17:54 UTC, IvanPlastun commented on src/pug/pages/ui/footer.pug
> +					.container.footer__container
Изменить отступ у элемента с классом `.footer__container`, установить `padding-top: 60px` и `padding-bottom: 80px`

2018-12-05 17:54 UTC, IvanPlastun commented on src/pug/pages/ui/footer.pug
> +							.col-4.footer__copyright
У элементов с классами `col` обнулить внутренние отступы по дизайну их нет.

2018-12-06 21:54 UTC, EvgeniyaRo commented on src/less/sections/_footer.less
> +	padding: 0 0 25px 0;
Исправлено

2018-12-06 21:58 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +
Не понимаю замечания про контент внутри колонок. у меня контент внутри колонки, есть табуляция, все нормально. Может я не так что понимаю?

2018-12-06 22:02 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +								a(href="#!") Контакты
Исправила

2018-12-06 22:30 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +
сделала так, но мне кажется, что транзишн не срабатывает
`.social {
	a {
		.transition;
		margin-right: 40px;
		
		:hover {
		color: #ffe400;
		}
	}
	
	:last-child {
		margin-right: 0;
	}	
}`

2018-12-06 22:31 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +
миксин с сылками исправила, параметры исправила

2018-12-06 22:33 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +					.container.footer__container
исправила

2018-12-06 22:36 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +							.col-4.footer__copyright
исправила

2018-12-06 22:46 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +
.footer__nav на nav.footer__nav  -  заменила

2018-12-06 22:57 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +
![image](https://user-images.githubusercontent.com/35632103/49616902-66985b80-f9c3-11e8-9ea1-80bf54de7392.png)

2018-12-06 23:03 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +
Исправила

2018-12-06 23:08 UTC, EvgeniyaRo commented on src/pug/pages/ui/footer.pug
> +							.col-4.footer__copyright
Обнулила паддинги, добавила класс .no-padding, получилось что-то не то

2018-12-07 09:01 UTC, IvanPlastun requested changes
Необходимы изменения.

2018-12-07 09:01 UTC, IvanPlastun commented on src/less/blocks/_icon-footer.less
> -
Перести в данный класс less-миксин transition, чтобы он корректно работал.

2018-12-07 09:01 UTC, IvanPlastun commented on src/less/sections/_footer.less
> +		.transition;
А тут удалить его.

2018-12-08 09:33 UTC, EvgeniyaRo commented on src/less/blocks/_icon-footer.less
> -
Исправлено

2018-12-08 09:33 UTC, EvgeniyaRo commented on src/less/sections/_footer.less
> +		.transition;
Исправлено

2018-12-08 10:59 UTC, IvanPlastun approved these changes
добавить к блоку с классом `row` утилитарные классы `ml-0` и `mr-0`. И в документации не забудьте обновить код секции. После того как сделаете это, устраняйте конфликты и выполняйте слияние в develop.

2018-12-08 12:41 UTC, merged