Blog post
IvanPlastun/webdev-team02 pull request #20
Opened 2018-12-05 17:38 UTC by evgeniy-ofitserov

@IvanPlastun Прошу проверить. Все готово

2018-12-06 09:37 UTC, IvanPlastun commented
1)Не нужно создавать несколько переменных с одинаковыми значениями, лучше создать одну обобщенную и использовать её. Удалить переменную `@userName` и оставить `@textContent`.
2)Не нужно добавлять к заголовку h1 свойство `font-size: 28px;`, поскольку это значение уже установлено для него в файле `_user-content.less`. 
3) Обнулить внешние отступы у заголовка `h1` установить `margin: 0;`
4)Изменить цвет заголовка, в макете его цвет вот такой `#222`
5) Установить размер шрифта(`font-size`) и начертание(`font-weight`) для блоков с классами:
`post-info__author`, `post-info__date`, `post-info__topic`, `post-info__comment`. Равными: `font-size: 14px;`, `font-weight: 600;`
6) Заменить изображения к посту блога на изображение из макета.
7) У параграфов с классами `post-text__content` обнулить внешние отступы `margin: 0`. У первого параграфа установить отступ снизу `margin-bottom: 20px`
8) Переименовать классы post-text заменить на `post-content`, а класс post-text__content заменить на `post-content__text`
9) Удалить лишние миксины для ссылок, сделать один универсальный например `postLink`, поскольку ссылки на данной секции отличаются друг от друга только размером шрифта и начертанием, лучше создавать между ними отличия с помощью модификаторов.
Вот пример миксина:
`mixin postLink(text, link) 
         a(src=link)&attributes(attributes) #{text}
`
10) Перенести секцию post-blog в навигации в файле ui-nav из страниц в блок с секциями, поскольку пост блога это секция, а не страница. 
11) Добавить код секции в документацию.

2018-12-06 15:23 UTC, evgeniy-ofitserov commented
@IvanPlastun Измения внесены

2018-12-06 17:04 UTC, IvanPlastun requested changes
1) Отступ от изображения до текста в параграфе `30px`, а не 40;
2) Задать для ссылок с классом `.postlink` эффект при наведении с цветом @blueHover - переменная уже есть в файле _variables.less
3) Создать в папке `pug/sections/` файл blog-post.pug и поместить в него только код секции без документации
4) Создать в папке `pug/pages/ui/` файл blog-post.pug и поместить в него документацию относящуюся к секции.

2018-12-06 18:15 UTC, evgeniy-ofitserov commented
@IvanPlastun Изменения внесены

2018-12-06 18:52 UTC, IvanPlastun requested changes
Требуются изменения.

2018-12-06 18:52 UTC, IvanPlastun commented on src/pug/pages/ui/blog-post.pug
> -.post
Документация должна быть оформлена вот так 
```
extends ../../layouts/ui-layout/ui-layout.pug

block variables
	- var title = 'Кнопки - UI-kit и HTML фреймворк - Документация';
	- var pageClass = 'body--dashboard';

block content
	.main-wrapper
		.container.container--left.user-content.pt-35
			h1 Пост в блоге
                        .section-ui
                               include ../../sections/blog-post.pug
                         pre.
                              include ../../sections/post-blog.pug
                          title-2 Код секции
                         pre.
                               // вот тут код секции
                    
``` 
Оставить blog-post.pug в папке ui. Файл block-post.pug удалить.

2018-12-06 20:29 UTC, evgeniy-ofitserov commented
@IvanPlastun Исправлено, прошу проверить

2018-12-07 08:05 UTC, IvanPlastun requested changes
Переименовать файл стилей с _block-post.less на `_blog-post.less`. И отредактировать код внутри файла стилей, а то не совсем понятно, где вложенность, а где самостоятельные стили.

2018-12-07 15:24 UTC, evgeniy-ofitserov commented
@IvanPlastun Изменения внесены

2018-12-07 17:20 UTC, IvanPlastun approved these changes
Все, теперь все хорошо) Можно устранять конфликты, если они есть и сливать ветку в develop.

2018-12-09 10:28 UTC, merged