Massage user
IvanPlastun/webdev-team02 pull request #21
Opened 2018-12-06 12:10 UTC by IrinaVSerova

2018-12-06 15:57 UTC, IvanPlastun requested changes
1) Переименовать класс в секции с fon-massage(massage - переводится как "массаж", а у нас тут массажей и близко нету), нам нужен `message - сообщение`. Поэтому переименуйте это класс и сделайте вот такой: `message-user`.
2) Не нужно задавать классы заголовков к блокам. Удалить у блоков классы `title-6, title-4 и другие классы связанные с title` и date-massage переименовать на `message-user__date` и стили для даты задавать в нем.
3) Удалить у блока класс title-4, это блок в котором находится текст с именем и email. Задать для него класс `message-user-info`. Внутри данного блока имя `Джон До' обернуть в тег span и задать для него класс `message-user-info__name` и стили к имени задавать через него.
4) Для email в этом же блоке создать ссылку `a(href="#!")`, а не блок div и ссылке задать класс message-user-info__email и стили для ссылки задавать через этот класс.
5) У параграфа удалить класс paragraph и класс text-massage переименовать на `message-user__text`. Также у этого параграфа обнулить внешние отступы `margin: 0` и задать отступы по макету.
6) Удалить у блока в котором находится текст `Прикрепленные файлы` класс tit;le-4 и установить для него класс `message-info-files`, а сам текст `Прикрепленные файлы` поместить в span, и для него задать класс `message-user-info-files__text` и в нем задавать стили для текста.
7) Заменить блок div, в котором находится текст `Avrora-platform.pdf` на ссылку `a(href="#!")` и задать для нее класс `message-user-info-files__link` и в нем задавать стили для этой ссылки.
8) Внутренние отступы(padding) у данной секции равны: 20px сверху 20px справа 20px слева 25px снизу. 
9) Задать заголовку h1 класс `message-user-title` и обнулить для него внешние отступы `margin: 0`, установить `margin-bottom: 30px` и задать стилизацию для заголовка. Начертание для заголовка по макету `font-weight: 700`, а не 900 как у вас установлено.

2018-12-06 17:48 UTC, IrinaVSerova commented
хорошо, что-то я и не посмотрела, про массаж)))) исправляю

2018-12-07 11:19 UTC, IvanPlastun requested changes
Добавить элементам ссылкам атрибут `href="#!"`.
Добавить ссылкам эффект при наведении `:hover`. При наведении изменять цвет ссылок свойством
`color: @blueHover`. Переменная `@blueHover` уже есть в файле variables.less, который лежит в папке base.

2018-12-07 11:19 UTC, IvanPlastun commented on src/less/sections/_message-user.less
> +  margin: 0;
Установить у заголовка отступ скнизу 'margin-bottom: 30px' вот тут в этом классе, утилитарный класс `mb-30` удалить. В этом же классе установить для заголовка начертание `font-weight: 700 !important;`. У вас он не устанавливается классом `strong`, потому что он имеет приоритет меньше чем вот этот селектор `.user-content h1`. Поэтому установите тут начертание вот так: `font-weight: 700 !important`.

2018-12-07 11:19 UTC, IvanPlastun commented on src/less/sections/_message-user.less
>    text-decoration: underline;
Установить значение свойства `text-decoration: none;` по дизайну у email нет подчеркивания.

2018-12-07 11:19 UTC, IvanPlastun commented on src/less/sections/_message-user.less
> +
В данный класс, добавить следующие свойства:
`    
    text-decoration: underline;
    font-weight: 400;
    margin-left: 30px;
`
У ссылки с этим классом утилитарный класс `ml-10`

2018-12-07 11:19 UTC, IvanPlastun commented on src/less/sections/_message-user.less
> +  margin: 0;
В данном классе установить отступы вот так:
`margin: 20px 0 25px 0 !important;`
И установить высоту строки
`line-height: 1.5 !important;`.

2018-12-07 11:19 UTC, IvanPlastun commented on src/pug/pages/ui/message-user.pug
>  			pre.
В данный тег `pre` добавить код секции, который находится в файле sections/message-user.pug.

2018-12-07 11:19 UTC, IvanPlastun commented on src/pug/sections/message-user.pug
> +.main-wrapper
Удалить вот тут класс `.main-wrapper`

2018-12-07 11:22 UTC, IvanPlastun requested changes

2018-12-07 11:22 UTC, IvanPlastun commented on src/pug/pages/ui/message-user.pug
> +
В данном теге pre удалить лишние пробелы. Чтобы на странице он корректно отображался.

2018-12-08 06:55 UTC, IrinaVSerova commented on src/less/sections/_message-user.less
> +  margin: 0;
убрала утиллитарные классы, поставила в свойства селектора

2018-12-08 06:56 UTC, IrinaVSerova commented on src/less/sections/_message-user.less
>    text-decoration: underline;
установила, сработало только после того как поставила атрибут

2018-12-08 06:57 UTC, IrinaVSerova commented on src/less/sections/_message-user.less
> +
добавила, но марджин сработал только в классе ml-30 (((, ...

2018-12-08 06:57 UTC, IrinaVSerova commented on src/less/sections/_message-user.less
> +  margin: 0;
сделала

2018-12-08 06:58 UTC, IrinaVSerova commented on src/pug/pages/ui/message-user.pug
>  			pre.
доюавила

2018-12-08 06:58 UTC, IrinaVSerova commented on src/pug/sections/message-user.pug
> +.main-wrapper
убрала

2018-12-08 07:36 UTC, IvanPlastun requested changes
Требуются изменения.

2018-12-08 07:36 UTC, IvanPlastun commented on src/less/sections/_message-user.less
>    margin: 0;
Добавить к данному свойству `margin: 0;` !important

2018-12-08 07:36 UTC, IvanPlastun commented on src/less/sections/_message-user.less
> +  margin-bottom: 30px;
Добавить к данному свойству `margin-bottom: 30px;` !important

2018-12-08 07:36 UTC, IvanPlastun commented on src/less/sections/_message-user.less
>    line-height: @LineHeightBase;
Для данного свойства `line-height` установить значение `1`, значение 1.5 задавать не нужно, поскольку это одна одна и она не будет переноситься на новую строку или содержать несколько строк.

2018-12-08 07:36 UTC, IvanPlastun commented on src/less/sections/_message-user.less
>  .message-user__text {
У блока с данным классом удалить утилитарный класс `mt-20` отступы уже установлены в данном селекторе, утилитарный класс не нужен. Вот они `margin: 20px 0 25px 0 !important;` зачем утилитарный класс, если тут отступы уже стоят.

2018-12-08 09:16 UTC, IrinaVSerova commented on src/less/sections/_message-user.less
>  .message-user__text {
убрала

2018-12-08 09:17 UTC, IrinaVSerova commented on src/less/sections/_message-user.less
>    line-height: @LineHeightBase;
это ведь про почту!? исправила

2018-12-08 09:49 UTC, IvanPlastun requested changes
1) В документации в коде секции у блока с классом `.message-user__title` удалить утилитарный класс `mt-20`. Вы же обновили код секции, не забывайте обновлять документацию.
2) У даты установить `line-height: 1;` т.к. это тоже одна строка и она не будет переноситься на новую строку.

2018-12-08 11:16 UTC, IvanPlastun approved these changes
Все хорошо, устраняйте конфликты и выполняйте слияние в develop.

2018-12-09 10:36 UTC, merged