About me edit work experience page ready
IvanPlastun/webdev-team02 pull request #25
Opened 2018-12-10 14:26 UTC by longsightedfilms

2018-12-11 08:23 UTC, IvanPlastun requested changes
1) Заменить имя класса `.content-padding` на что-нибудь более подходящее для блока, например `content-exp-page` или `content-page`. Класс блока должен отвечать на вопрос, что, и характеризовать блок, а не указывать на его состояние или поведение. 
2) У блока с этим классом `padding-bottom: 120px`. Необходимо поменять, у вас стоит 80px;
3) У заголовка h1 обнулить внешние отступы `margin: 0` и задать отступ снизу `margin-bottom: 35px`. Также у заголовка установить начертание `font-weight: 700;` и цвет `color: #222`
4) У параграфа с классом `message-user__text` - отступ сверху оставить в `20px`, отступ снизу должен быть `0`. Учитывайте при этом, что данный класс используется в другом блоке, чтобы не сломать его. Поэтому задайте для него собственный класс или же создайте модификатор для этого блока, чтобы должным образом стилизовать его.
5) Текст `Добавить новое место` является заголовком 3-го уровня, а не 2-го как у вас. Установив нужный заголовок сбросить у него внешние отступы `margin: 0;` У блока, который стоит выше этого текста, удалить утилитарный класс `mb-20` и установить `mb-30`,  должно быть 35px, но мы устанавливаем 30 c учетом высоты строки заголовка. Отступ от данного заголовка до формы равен `margin-bottom: 35px`.
6) Отступ между элементами input и textarea равен `20px`, а не 18px.
7) В миксине previousJob текст с описанием лучше сделать через `block`, поскольку данный текст занимает много места, и не удобно добавлять его через параметр.

2018-12-11 12:51 UTC, longsightedfilms commented
Залил правки

2018-12-11 19:24 UTC, IvanPlastun requested changes
1) У заголовка h1 удалить свойство  `margin-bottom: 35px` и добавить отступ с помощью утилитарного класса `mb-35`. Чтобы данный отступ не применялся к другим подобным заголовкам, на других страницах.
2) Отступ снизу между первым и вторым блоком с классом `.message-user` 20px и от второго блока, до заголовка с текстом `Добавить новое место`, тоже 20px. Я ошибся в прошлый раз не учет высоту строки заголовка, указав вам, что отступ должен быть 30px.
3) У заголовка h3 установить `font-weight: 700;`. Отступ вниз для данного заголовка установить с помощью утилитарного класса `mb-35`, а `margin-bottom: 35;` в селекторе удалить.

2018-12-12 08:29 UTC, longsightedfilms commented
Залил правки

2018-12-12 08:49 UTC, IvanPlastun approved these changes
Все хорошо, но надо у заголовка h3 установить `color: #222;` После этого проверяйте есть ли конфликты, если есть устраняйте и выполняйте слияние в develop.

2018-12-12 08:55 UTC, merged