works ready
IvanPlastun/webdev-team02 pull request #26
Opened 2018-12-10 15:56 UTC by chl9252

"Работы" на проверку

2018-12-11 08:48 UTC, IvanPlastun requested changes
1) Блоку с классом .row не нужно задавать `margin-bottom: 50px` т.к. это влияет на другие блоки, которые используют данный класс. Данный отступ необходимо удалить, и если хотите добавить отступы между рядами используйте либо утилитарные классы, или создайте свой класс модификатор для отступов, но лучше использовать именно утилитарные классы.
2) Обнулить у всех колонок внутренние отступы слева и справа и задавать отступы между колонками с помощью margin, используя утилитарные классы.
3) У жирного текста в заголовке начертание font-weight должно быть равно `700`, а не 800. отступ снизу `margin-bottom` от данного заголовка должен быть `35px`.
4) У блока с классом `.container` padding-bottom по дизайну равен `120px`

2018-12-11 10:18 UTC, chl9252 commented
Исправила

2018-12-11 18:37 UTC, IvanPlastun requested changes
1) У блока с классом `.container` заменить утилитарный класс `pt-70` на `pt-80`.
2) Для span задать класс модификатор, то есть вместо works-span, сделать `works-title-text--bold`. Думаю так лучше.
3) Создать в ui страницу с документацией для вашей работы, подобно тому, как мы делали это для секций.

2018-12-12 07:08 UTC, chl9252 commented
Исправила. На первый экран ссылку на "Работы" добавила.

2018-12-12 07:55 UTC, IvanPlastun approved these changes
Все хорошо, если есть конфликты устраняйте их и выполняйте слияние в develop.

2018-12-12 07:59 UTC, merged

2018-12-12 08:01 UTC, chl9252 commented
Слияние в develop проведено