home page complete
IvanPlastun/webdev-team02 pull request #27
Opened 2018-12-10 18:25 UTC by iiMikhail

Главная страница готова.
@IvanPlastun , @nobleworkshop  прошу проверить.

2018-12-11 17:02 UTC, IvanPlastun requested changes
1)Обнулить отступ у заголовка h1 и задать отступ `margin-bottom: 20px;` и начертание `font-weight: 700;`.
2) Обнулить отступы у элементов `p.paragraph` и установить `margin-bottom: 20px;` между параграфами. Высота строки у параграфов по дизайну `line-height: 1.5;`, а установлено 2em;
3)В блоках, у которых установлены классы колонок обнулить padding и задать внешние отступы margin между колонками, чтоб отступы не складывались и не смешивались, внешние и внутренние. Сброс отступов задавай с помощью класса модификатора.
4) Отступ от параграфа до текста `Что я умею` установить `margin-bottom: 30px`. У данного заголовка с текстом `font-weight: 700;`, цвет текста `color: #222;`. Отступ снизу `margin-bottom: 15px;`. 
По дизайну после этого заголовка идет два параграфа и видимо они там не просто так, т.к. содержат две разные мысли. Расстояние между этими заголовками `margin-bottom: 20px`
5) У блока с классом `.section` удалить свойства `margin-top: 80px;` и `margin-bottom: 80px;` и заменить их на `padding-top, padding-bottom`. Решить проблему отступов задаваемых данным классом т.к. расстояние между первым рядом с карточками должно быть `80px` по дизайну, а у тебя получается 160px, т.к. отступы, которые задаются данному классу складываются, такого быть не должно.
6) Текст `Новые работы` поместить в тег `span` и задать для него стилизацию, потому что на странице может быть только один заголовок h1. Отступ `margin-bottom` от данного заголовка равен `30px` для установки используй утилитарный класс `mb-30`.
7) У колонок `col-md-4` и у других блоков с колонками обнулить отступы `padding` с помощью класса модификатора и отступы между карточками установить с помощью `margin`. Расстояние между карточками равно `30px`.
8) Заголовок с текстом `Новые записи с блоге` обернуть в `span` и стилизовать его.  На странице может присутствовать только один заголовок h1.

2018-12-13 07:34 UTC, iiMikhail commented
Готово!
@IvanPlastun , @nobleworkshop  прошу проверить

2018-12-13 10:32 UTC, IvanPlastun requested changes
1)У параграфов в блоке с классом `about-me__description` задать `margin: 0;`. Установить только отступ снизу между параграфами `margin-bottom: 20;` с помощью утилитарного класса.
2) У заголовка с классом `.title-1--weight` удалить margin-bottom т.к. отступ вниз в `10px`. 10px - потому что высота строки равна где-то около 10px. А отступ между данным заголовком и параграфом должен быть 20px, Как раз и получиться высота строки + 10px снизу = 20px.
3) Переделать блок с описанием не соответствует макету. Отсутствует блок `Что я умею`
4) Отступ от параграфа до кнопки с текстом `Подробнее` равен 40px. Отступы между элементами при сборке страницы лучше задавать с помощью утилитарных классов, если это возможно.
5) Заголовок с текстом `Новые работы` переделать он не должен быть заголовком `h1`. На странице может присутствовать только один заголовок `h1`. Отступ `margin-bottom: 10px` у данного заголовка установленный в классе `title-1--weight`  удалить. Будет автоматически установлен отступ в 30px снизу т.к. он находится в колонке. Почему модификатор называется `--weight - вес?`
6) Исправить отступы между блоками с контентом.
7) Отступ от карточек до блока с footer-м равен `120px`
8) Заголовок с  текстом `Новые записи в блоге` не должен быть `h1`. На странице может присутствовать только один заголовок 1-го уровня.

2018-12-13 12:43 UTC, iiMikhail commented
Внес изменения.
Прошу проверить.

2018-12-14 10:04 UTC, IvanPlastun requested changes
1) Удалить `margin-bottom: 80px` у блока `header` т.к. данный отступ будет влиять на отступы на других страницах. Добавить утилитарный класс с отступом к блоку `main__wrapper`, и да почему данный класс является элементом существующим без блока. Необходимо поправить `! Элементы не могут существовать за пределами блока или без блока`, переименовать.
2) Использовать при стилизации стили для типографики либо из файлов `titles.less и text.less` или использовать только стили из `_user-content.less`. Потому что при использовании стилей из файлов `titles.less и text.less` стили из файла _user-content.less перестают применяться.
3) ! Не нужно задавать отступы так, чтобы происходило их сложение, необходимо задавать отступы либо вниз либо вверх, от элементов, а не задавать по чуть-чуть от одного элемента вниз и чуть-чуть от другого элемента вверх, это не правильно. Получается каша из отступов.
! Обнулить отступы у параграфов и установить их с помощью утилитарных классов равными `20px`
Отступ от заголовка с текстом `Емельян Казаков` ! `margin-bottom: 10px`
Отступ снизу от параграфа с текстом до заголовка `Что я умею` `margin-bottom: 20px` с учетом высоты строки.
Отступ снизу от заголовка с текстом `Что я умею` до параграфа расположенного под ним `margin-bottom: 5px;`
4) У заголовка с текстом `Новые работы`: `font-weight: 700; font-size: 28; color: #222;`
5) Отступ от заголовка `h2 Новые работы` `margin-bottom: 45px` удалить. Тут должен быть отступ в 30px он устанавливается автоматически т.к. заголовок расположен в колонке.
6) Отступ от заголовка с текстом `Новые записи в блоге` до карточек равен `margin-bottom: 45px`. У данного заголовка `font-size: 28px; font-weight: 700; color: #222;`

2018-12-19 11:13 UTC, iiMikhail commented
Готово. Коммит внес.
@IvanPlastun , @nobleworkshop  прошу проверить.

2018-12-19 13:02 UTC, IvanPlastun approved these changes
Все хорошо. Устраняй конфликты и выполняй слияние в develop.

2018-12-20 08:26 UTC, merged