Page about edit information
IvanPlastun/webdev-team02 pull request #28
Opened 2018-12-10 19:39 UTC by ser-kiselev

Страница «Обо мне редактировать – Информация» собрана.

2018-12-11 18:16 UTC, IvanPlastun requested changes
1) У блока с классом `.about-me-edit` установить padding-top: 80px;
2) Не следует задавать классы заголовков блокам, поэтому оберните текст `Редактировать обо мне` в тег h1 сбросьте у него `margin: 0`, с помощью класса модификатора. И установите для него `margin-bottom: 35px` и `font-weight: 700;`
3) У блока с классом `edit-name` удалить `margin-top: 37px`.
4) Удалить у блока с классом `.upload__result` `margin-bottom` и добавить его к блоку с классом `upload-photo` с помощью утилитарного класса `mb-35`.
5) Создать в папке less каталог pages и в нее поместить файл со стилями для страницы. Выполнить подключение файла со стилями в блоке `Pages` внутри файла main.less.

2018-12-11 19:17 UTC, ser-kiselev commented
Внёс необходимые правки.

2018-12-11 20:48 UTC, IvanPlastun requested changes
У блока с классом `upload-photo` удалить свойство `margin-top: 30px;` и добавить отступ с помощью утилитарного класса `mt-30`.

2018-12-12 16:51 UTC, ser-kiselev commented
Внёс правки.

2018-12-12 18:01 UTC, IvanPlastun requested changes
1) Цвет текста для заголовка h1 установить `color: #222;`.
2) Элементы с классами `edit-name`, `upload-photo`, `edit-information`, `about-me-edit-buttons` обернуть в тег `form`.
3) У кнопки `Отмена` должен быть тип `submit.`

2018-12-12 19:08 UTC, ser-kiselev commented
1. Поменял цвет заголовка.
2. Обернул в тег form.
3. Сменил тип кнопки «Отмена» с reset на submit.

2018-12-12 19:39 UTC, IvanPlastun approved these changes
Все хорошо, устраняйте конфликты и выполняйте слияние в develop.

2018-12-12 20:56 UTC, merged