user-profile - ready
IvanPlastun/webdev-team02 pull request #29
Opened 2018-12-11 06:38 UTC by sanata713

2018-12-11 10:08 UTC, IvanPlastun requested changes
1) Отступ сверху в блока с классом `.content-padding` равен `80px`, а отступ снизу `padding-bottom: 120px`.
2) Спозиционировать кнопку `Редактировать` абсолютно. Добавить к блоку с классом `.user-profile-block`, `position: relative;`, а все свойства относящиеся к flex-box удалить. Кнопке же с классом `.user-profile__button` добавить `position: absolute;` и `right: -110px;`.
3) Если вы хотите, чтобы текст `Профиль` был заголовком, то оберните его в тег `h1`, обнулите у него внешние отступы `margin: 0px;` Установите начертание `font-weight: 700;` т.к. по дизайну у всех заголовков `h1` начертание равно 700. Не следует устанавливать классы заголовков блокам.
4) `! Неверные наименования классов.` Переименовать классы: 
`.user-profile-block--information`, `.user-profile__title--comments`. `--information и --comments` - это модификаторы, а модификаторы в БЭМ используются для изменения состояния или поведения, блока или элемента. Модификатор должен отвечать на вопрос `Какой?` указывая на признак, например белый, большой, малый и т.д. Блоки и элементы отвечают на вопрос `что?`. Элементы: это текст, кнопка, пункт меню. Блоки: header, footer, main и т.д.
4) Если решили сделать текст `Комментарии пользователя` заголовком, то также оберните его в тег h2 и выполните действия аналогичные, что и над заголовком h1. К заголовку с данным текстом добавьте утилитарный класс `mb-20`.
5) У блока с классом `.user-profile-block--comments` удалить `padding-top: 25px` и `padding-bottom: 40px`. У вас вроде в этом классе больше ничего нет, из стилей, поэтому можно удалить данный селектор целиком.
6) В блоке с avatar-ом и информацией удалить внутренние отступы padding. И задать внешние с помощью утилитарных классов: `mb-40` и `mt-40`.
7) У блока с классом `.user-profile__description` удалить внутренний отступ `padding-left: 50px` и `margin-bottom: 20px`, установить `margin-left: 50px;` Внутренние отступы задают отступ от внешней границы блока до его содержимого, внешние отступы, задают отступ от внешнего контейнера и от соседних элементов, учитывайте это при задании отступов.
8) Отступ сверху у элемента `.user-profile__description p` равен 10px.
9) У блока с классом `.user-profile-block--comments` удалить `padding-top: 25px;` и `padding-bottom: 40px;`
10) У последнего элемента с классом `.user-comment`  с помощью псевдокласса `:last-child` обнулить `margin-bottom: 0`;
11) Расстояние между иконкой часов и датой в блоке с комментарием равно `10px`. Удалите отступ в 30px, который у вас установлен, его там быть не должно. Расстояние между ними по умолчанию уже 10px.
12) Отступ справа у блока с классом `.user-comment__article-title` равен `20px`. Изменить его, потому что у вас он установлен 30px. Текст в данном блоке синего цвета, это значит, что скорее всего он является ссылкой, на статью, в которой пользователь оставил комментарий, поэтому оберните его в тег `a` и выполните его стилизацию.

2018-12-11 12:40 UTC, sanata713 commented
Поправила ошибки

2018-12-11 20:09 UTC, IvanPlastun requested changes
Уже ошибок, меньше, но необходимы изменения)
1) Элементу с классом `.user-profile__button` добавить свойство `top: 0`. А у блока с классом `.user-profile-block` удалить свойство `justify-content: space-between`
2) Переименовать класс content-padding на `content--padding` - это модификатор, у вас он используется для задания отступов, соответственно должен именоваться вот так, а блоком у вас является `.container`.
3) У заголовка h2 по дизайну `font-weight: 600;`. 700 - для заголовков h1.
4) Удалить элемент span внутри ссылок в блоке с классом `.user-comments` и установить класс, который задан у span к ссылке. Добавить для данных ссылок эффект при наведении `:hover`, который будет изменять её цвет, для изменения цвета используйте переменную `@blueHover`, которая определена в файле `_variables.less`.
5) Создать в ui  страницу с документацией для вашей работы, аналогично тому, как мы это делали при создании секций.

2018-12-12 05:36 UTC, sanata713 commented
@IvanPlastun Поправила почти всё. Не разобралась, как убрать span, все у меня съезжает сразу, что-то не то делаю, видимо, Эффект у ссылки по наведению сделала. Блок на страницу index.pug тоже добавила.

2018-12-12 08:33 UTC, IvanPlastun requested changes
1) Установить у заголовка h1 `font-size: 28px`
2) Переименовать класс `user-comment__text--profile` на `user-comment__text-profile`. Элементы не могут быть модификаторами. Чтобы задать к элементу модификатор используется вот такая конструкция. `name__elem` - это сам элемент и вот элемент с модификатором `name__elem name__elem--color` - вот так к элементу добавляется модификатор.
3) Заголовку с классом `user-profile-text` установить `font-size: 26px`.
4) Удалить у элемента span с классом `user-comment__article-title` margin-right: 20px и добавить его к ссылке с помощью утилитарного класса `mr-20`.
5) Добавить к элементу с классом `user-comment__text-profile` `line-height: 1.5;`, потому что комментарий может состоять из нескольких строк.
6) У блока с классом `user-comment` изменить padding на `padding: 15px 20px`. 15px сверху устанавливается потому что, к элементу с текстом комментария была добавлена высота строки.

2018-12-12 09:57 UTC, sanata713 commented
@IvanPlastun Поправила

2018-12-12 16:48 UTC, IvanPlastun approved these changes
Все хорошо, только необходимо поправить у элемента с классом `user-comment__date .fa-clock` установив `margin-right: 10px !important;`. После того как это сделаете, устраняйте конфликты и выполняйте слияние в develop.

2018-12-12 17:34 UTC, merged