page-contacts-edit are ready
IvanPlastun/webdev-team02 pull request #30
Opened 2018-12-11 12:56 UTC by natalia-kaseeva

2018-12-11 17:36 UTC, IvanPlastun requested changes
1) У блока с классом `.contacts-edit__form` изменить отступ с margin-top: 45px на `margin-top: 40px;;`
2) У заголовка `h1` установить: `font-weight: 700;`, `color: #222;`
3) У блоков с классами `.col-md-3` сбросить `padding: 0px;` c помощью класса модификатора и установить расстояние между колонками с помощью `margin`. Расстояние между колонками равно `30px`. 
4) Сделать страницу с документацией.
5) Переименовать классы `.contacts-edit__form-button--save` и `.contacts-edit__form-button--cancel` на `.contacts-edit__form-button-save`  и `.contacts-edit__form-button-cancel`.

2018-12-12 14:47 UTC, natalia-kaseeva commented
@IvanPlastun Внесла изменения. 
Сделала файл с документацией, добавила ссылку на данную страницу на главной странице. 

Убрала все боковые отступы у общего блока и строк, но у колонок решила оставить стандартные padding по 15px, т.к.если делать разные внутренние отступы у блоков, то они становятся разного размера, что плохо смотрится на странице

2018-12-12 17:25 UTC, IvanPlastun requested changes
1) Обнулить у заголовка с классом `.contacts-edit__title-text` `margin: 0;`.
2) Заменить div.contacts-edit__form на `form.contacts-edit__form`, чтобы данный блок был формой, внутри которой находятся поля формы.

2018-12-12 17:39 UTC, natalia-kaseeva commented
@IvanPlastun Внесла изменения

2018-12-12 18:17 UTC, IvanPlastun approved these changes
Все верно, устраняйте конфликты, если они есть и выполняйте слияние в develop.

2018-12-12 19:28 UTC, merged