About me edit technologies page ready
IvanPlastun/webdev-team02 pull request #32
Opened 2018-12-12 11:36 UTC by longsightedfilms

2018-12-12 19:00 UTC, IvanPlastun requested changes
1) Кнопка отмена должна создаваться с помощью миксина +buttonSubmit()
2) Для элементов форм сделать 3 ряда, в которых будут находится кнопки и полями ввода.
3) Удалить блок с классом `w-100` и данный класс тоже удалить.
4) Отступы между рядами необходимо задавать с помощью утилитарных классов.
5) Удалить утилитарные классы `mb-40` у блоков с классом `about-me-tech__input`.
6) Параграфу с классом `.percent` переопределить стили  указав их в следующем порядке:
`align-self:center;` затем `margin: 0;`, `margin-left: 5px;` и `margin-right: 10px;`.

2018-12-13 11:23 UTC, longsightedfilms commented
Залил правки

2018-12-14 11:27 UTC, IvanPlastun requested changes
1) Переделать. Ваш код должен выглядеть вот так:
`					h1.title-1.mt-0.mb-35 Редактировать - Технологии
					form
						.row.mb-40
							.col-3
								.about-me-tech__input
									+input('html5','text','0','HTML5')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('css3','text','0','CSS3')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('js','text','0','JS')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('jquery','text','0','jQuery')
									p.percent %
						.row.mb-40
							.col-3
								.about-me-tech__input
									+input('php','text','0','PHP')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('mysql','text','0','MySql')
									p.percent %
						.row.mb-30
							.col-3
								.about-me-tech__input
									+input('git','text','0','Git')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('gulp','text','0','Gulp')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('bower','text','0','Bower')
									p.percent %
							.col-3
								.about-me-tech__input
									+input('webpack','text','0','WebPack')
									p.percent %
						.row
							.col-auto
								+buttonSubmit('Сохранить', 'save-button', 'save')(class="mr-20")
								+buttonSubmit('Отмена', 'cancel-button', 'cancel')`

2018-12-14 12:52 UTC, longsightedfilms commented
Переделал страницу

2018-12-14 16:25 UTC, IvanPlastun requested changes
Вот тут сделано не верно, думайте и будьте внимательны когда делаете.
`.row
	.col-auto	
                +buttonSubmit('Сохранить', 'save-button', 'save')(class="mr-20")
	.col-auto
		+buttonSubmit('Отмена', 'cancel-button', 'cancel')`
Если вы создаете две колонки то (class="mr-20") не нужен, удалите его и сделайте вот так:
`.row
	.col-auto.pr-30
                +buttonSubmit('Сохранить', 'save-button', 'save')
	.col-auto
		+buttonSubmit('Отмена', 'cancel-button', 'cancel')`
Если вы хотите должны образом поставить кнопку.

2018-12-15 11:49 UTC, longsightedfilms commented
Ещё раз подправил страницу, теперь должно быть как на макете

2018-12-15 14:13 UTC, IvanPlastun approved these changes
Все хорошо, ошибок нет, но в документации удалить код, который отображает страницу и заменить его одной строкой `include ../название_страницы.pug` не надо писать код целиком когда есть уже готовая страница. После выполнения данного изменения ещё раз внимательно просмотрите код устраняйте конфликты, при устранении конфликтов так же внимательно смотрите, что удалить, а что оставить и после выполняйте merge в develop.

2018-12-16 11:34 UTC, merged