user-profil-edit ready
IvanPlastun/webdev-team02 pull request #34
Opened 2018-12-12 19:44 UTC by chl9252

"Профиль пользователя - редактировать" на проверку

2018-12-13 09:12 UTC, IvanPlastun requested changes
1)Удалить блоки с классами `user-edit-buttons--left` и `user-edit-buttons--right` они не нужны, т.к. кнопки и так должным образом будут спозиционированы.
2) Установить ширину для блока с классом `user-edit-wrapper` `max-width: 33.33333333%`
3) Заголовок с текстом `Фотография` должен быть заголовком `h6`, а не h3. Посмотрите в файл `less/sections/_user-content.less`. Стили для заголовка у вас верные, но тип заголовка нет.
4) Переименуйте класс `user-edit-fam` на `user-edit-lastname`

2018-12-13 09:57 UTC, chl9252 commented
Исправила

2018-12-13 11:18 UTC, IvanPlastun requested changes
1) Удалить у блока с классом `user-edit-name` утилитарный класс `mt-35` и перенести его первому блоку с классом `user-edit-wrapper`
2) Обернуть блоки с классами `user-edit-wrapper` и `user-edit-foto` в тег `form`
3) `! Неправильно выполнено добавление секции с загрузкой файла c изображением.` В папке `pug/sections/` есть файл `upload-file-no-img.pug`, в котором находится код готовой секции и вы должны его использовать. Мы верстали секции для того чтобы их использовать и экономить себе время, а не верстать секции с нуля. Выполните добавление данной секции вот так: `include ../sections/upload-file-no-img.pug` 
4) Удалите лишние классы и селекторы в Less. которые вы использовали при верстке данной секции.

2018-12-13 12:16 UTC, chl9252 commented
Исправила

2018-12-14 10:29 UTC, IvanPlastun requested changes
1) Так как блоки были обернуты в тег form, то необходимо удалить у первого блока с классом `user-edit-wrapper` утилитарный класс `mt-35` и перенести его к тегу form
2) Удалить у блока с классом `user-edit-land` утилитарный класс `mt-30` и добавить его к родительскому блоку `user-edit-wrapper`
3) Кнопка `Отмена` должна быть создана с помощью миксина `+buttonSubmit`.

2018-12-14 11:02 UTC, chl9252 commented
Исправила

2018-12-14 12:01 UTC, IvanPlastun approved these changes
1) Изменить в документации текст переменной: - var title = 'Работы страница - UI-kit и HTML фреймворк - Документация'; Это страница с профилем, а не работы)
2) В документации удалить строку `../user-profil-edit.pug` она не нужна.
После выполнения данных изменений внимательно просмотрите код, если есть конфликты устраните их и выполняйте слияние в develop.

2018-12-14 12:50 UTC, merged

2018-12-14 12:52 UTC, chl9252 commented
var title  -  изменила
../user-profil-edit.pug  -  убрала
слияние в develop  -  сделала