contacts-messages-page ready
IvanPlastun/webdev-team02 pull request #35
Opened 2018-12-13 08:25 UTC by sanata713

2018-12-13 11:00 UTC, IvanPlastun requested changes
1) Не правильно выполнено подключение секций с сообщениями пользователей. Они находятся в секции и не нужно копировать код секций, чтобы добавить их к себе на страницу. Необходимо использовать `include` для подключения секций.
При подключении секции создайте блок, например с классом `.user-from-messages` и внутри этого блока выполняйте подключение секции с сообщением вот так `include ../sections/message-user.pug`
2) Удалите внутри файла, который находится в `pug/sections/message-user.pug` заголовок `h1` и добавьте его к себе на страницу, чтобы в данном файле были только секции с сообщениями. 
3) Расстояния между секциями на странице устанавливайте с помощью утилитарных классов.

2018-12-13 13:17 UTC, sanata713 commented
@IvanPlastun Поправки внесла. С первого раза коммит не ушел почему-то )

2018-12-14 11:08 UTC, IvanPlastun requested changes
1) Удалить лишние пустые строки в файле pug/pages/contact-message.pug.
2) Удалить блок с классом `visitor-messages-block` оставить только блоки с классом `user-from-messages` и к первому блоку с данным классом добавить утилитарные классы 'mt-30' и `mb-20`.
3) Отступы, которые были заданы с помощью селекторов  LESS удалить.

2018-12-14 11:40 UTC, sanata713 commented
@IvanPlastun Поправила всё.

2018-12-14 16:00 UTC, IvanPlastun approved these changes
.message-user-info-files__link {
    cursor: pointer;
}
Если данный класс ни где не используется удалите его.
А так ошибок больше нет, ещё раз внимательно просмотрите свой код, устраняйте конфликты и выполняйте слияние в develop.

2018-12-14 16:50 UTC, merged