blog ready
IvanPlastun/webdev-team02 pull request #38
Opened 2018-12-13 17:51 UTC by chl9252

страница Блог на проверку.
Извините, взяла новую, не сдав страницу. Но, "Блог" очень похож на "Работы". (Очень аккуратно буду с ветками обращаться)

2018-12-13 18:42 UTC, chl9252 commented
Нашла ошибку (в pre. не заменила) - исправлю с исправлением ошибок.

2018-12-14 10:48 UTC, IvanPlastun requested changes
1) Удалить блоки с классами `blog-title-left` и `blog-title-right` заголовок и кнопка без них будут должным образом спозиционированы.
2) У блока с классом `blog-title` заменить утилитарный класс `mb-35` на `mb-40`
3) В документации убрать лишние отступы между строками кода.  И отредактировать документацию.

2018-12-14 11:26 UTC, chl9252 commented
Исправила

2018-12-14 11:38 UTC, IvanPlastun approved these changes
Удалить данный блок в документации т.к. страницу готовую мы уже никуда подключать не будем.
`pre.
	include ../blog.pug`
После просмотрите ещё раз внимательно все по коду, устраняйте конфликты и выполняйте слияние в develop.

2018-12-14 12:19 UTC, merged

2018-12-14 12:21 UTC, chl9252 commented
pre. include ../blog.pug  -  удалила. По коду ничего не заметила. Слияние в develop произвела.