Works – separate work
IvanPlastun/webdev-team02 pull request #43
Opened 2018-12-14 20:34 UTC by ser-kiselev

Страница «Работы – отдельная работа» готова.

2018-12-15 16:19 UTC, IvanPlastun requested changes
1) Установить у иконки в логотипе утилитарный класс mr-0, именно у иконки, а не у блоков и добавить утилитарный класс блоку с классом `logo__img`
2) У блока с классом `logo__description` установить утилитарный класс `ml-50`
3) Перейдите в ветку develop выполните git pull после перейдите в вашу рабочую ветку и выполните `git merge develop`. Затем удалите у блока с классом `separate-work-head` `padding-top:120px;` И добавьте блоку с классом `logo` утилитарный класс `mb-120` он определен в утилитарных классах, если не определен определите его.
4) У колонки, в котором лежит кнопка `редактировать` изменить `col-3` на `col-2`ю
5) Ссылке с классом `separate-work-info__category` добавить эффект при наведении, изменения цвета ссылки. В качестве цвета используйте переменную `@blueHover` определенную в файле _variables.less
6) Удалить утилитарный класс `mt-55` у блока с классом `separate-work-image_img` и перенести его к блоку с классом `separate-work-image`.
7) Переименовать класс `separate-work-image_img` на `separate-work-image-preview`.
8) Заменить утилитарный класс `pb-50` у блока с классом `separate-work-header-bg` на `mb-50`.
9) У параграфа расположенного после заголовка `Коротко о проекте` переопределить стили указав их в следующем порядке `margin:0;` затем `margin-bottom: 20px`.
10) У элементов списка с классом `separate-work-technologies__list-item` `line-height: 1;` и отступ снизу между ними равен `margin-bottom: 20px;`. У последнего margin-bottom: 0;
11) Добавить к ссылке на проект и ссылке на github эффект при наведении, использовать переменную `@blueHover` из файла `_variables.less`.
12) Удалить утилитарный класс `mt-35` от заголовка с текстом `Код на github` и добавить к блоку с классом `separate-work-link-github` `mb-35`.
13) У параграфа, который расположен над кнопкой `Все работы` обнулить `margin-bottom: 0;`
14) У блока с классом `separate-work-pagination-wrapper` заменить утилитарный класс `mt-30` на `mt-45`.

2018-12-15 18:33 UTC, ser-kiselev commented
Внёс правки.

2018-12-17 07:24 UTC, IvanPlastun requested changes
1) У блока с классом `logo__img` заменить утилитарный класс mr-10 на `mr-15`
2) В LESS файла у функции `.bg-header` удалить пробел между названием функции и `(`
3) В документации в блок `.section-ui` не нужно копировать весь код страницы для её отображения. Используйте `include`.

2018-12-17 17:58 UTC, ser-kiselev commented
Отредактировал.

2018-12-17 18:19 UTC, IvanPlastun approved these changes
Все теперь все хорошо. Устраняйте конфликты, если они есть и выполняйте слияние в develop.

2018-12-17 18:22 UTC, merged