about-me
IvanPlastun/webdev-team02 pull request #44
Opened 2018-12-15 06:00 UTC by IrinaVSerova

2018-12-15 19:09 UTC, IvanPlastun requested changes
1) Удалить класс `.section-ui` у всех блоков где он у вас присутствует. Данный класс используется !Внимание, только в документации при сборке страницы его использовать не нужно.
2) Удалить блок кода.
`.header
       include ../sections/logo.pug
       .pt-15
             include/sections/navigation.pug
`
Не нужно было создавать блок header c нуля и верстать его.  У нас есть уже готовые секции, которые мы должны просто брать и подключать на страницу, которую собираем. Поэтому после того как удалите этот код и не забудьте удалить стили, которые вы для него писали. Подключите блок header к себе на страницу вот так:  `include ../sections/header-user.pug`
3) Класс `float-right` к кнопке редактировать нужно добавлять вот так : `+buttonSubmit("Редактировать", "edit-button", "edit")(class="float-right")` Внимательно смотрите документацию.
4) Не правильно задано именование классов `about__info-name, about__info-text, about__info-skills` и т.д. Все классы заданные подобным образом переименовать. Потому что это у вас это элементы существующие сами по себе без блока. А `элемент не может существовать без блока`. Посмотрите пожалуйста в документацию к проекту в раздел `Работа со стилями` >`Используем следующие правила BEM naming нотации для CSS классов`. 
5) Ряду, блоку с классом `.row`, в котором находится заголовок с текстом `Технологии` и кнопка редактировать добавить bootstrap-класс `justify-content-between`. У блока с классом `col-md-2`, который находится в данном ряду удалить класс `offset-md-4`.
6) У заголовка с классом `about__info-name' изменить св-во font-weight: 700 !important; на `font-weight: 700;` и установить ему font-size: 28px;
7) У параграфов к лассом `about__info-text` удалить свойство `margin: 5px 0 0 0;` и установить `margin: 0;`
8) От заголовка  `h1` c текстом `Емельян Казаков` установить отступ вниз `margin-bottom: 15px` с помощью утилитарного класса `mb-15`.
9) У блока с классом `about__info-text` width: 800px; зачем вы задаете блоку с текстом ширину? Она не нужна для текста в данном случае.
10) Отступ между параграфами расположенными после заголовка с текстом `Емельян Казаков` должен быть 15px у второго параграфа расположенного после заголовка `установить  отступ вниз с помощью утилитарного класса mb-15px`.
11) Обернуть текст `Что я умею` в заголовок h3 т.к. он является заголовком 3-го уровня. и переопределить для него стили . Установить вот такие свойства: `font-weight: 700;` !important не нужен `font-size: 24px;` и `margin: 15px 0 15px 0`
12)  Заменить утилитарный класс `mb-70` в блоке  `section__about-info` на `mb-65`
13) У блока с классом `section-indicators` удалить утилитарный класс `pb-30`.
14) В секции с индикаторами в блоке с классом `col-md-2`, в котором находятся элементы с текстом `Frontend, Backend и Workflow` удалить список `ul` вместе с этими элементами. И добавить в данную колонку просто 3 элемента `span` вот так: 
`col-md-2 
     span Frontend
     span Backend
     span Workflow
`
К данному блоку `col-md-2` добавить класс `flex-position-text`, в этом классе прописать следующие свойства: `display: flex; flex-direction: column; justify-content: space-around; margin-bottom: 61px; margin-top: 15px;`.
15) Текст `Технологии` обернуть в тег `p` и в стилях обнулить у него отступы `margin: 0;`, а затем установить отступ с помощь утилитарного класса `mb-10`.
16)  Текст `Которые используются в работе` обернуть в тег `p` и также обнулить у него отступы `margin: 0;` У элементов, которые были заменены со span на `p` удалить в стилях св-во `display: block`.

2018-12-16 07:18 UTC, IrinaVSerova commented
я и не прописывала класс .header с нуля, он ведь есть уже, я посмотрела, где находится эта картинка с пальмами и вставила этот класс

2018-12-17 14:06 UTC, IvanPlastun requested changes
1) Не правильный BEM-naming `about-info__name`, `about-info__text`, `about-info__skills`, у вас элементы все так же продолжают существовать без блоков. Необходимо исправить во всех местах, где есть такая ошибка.
Переименовывая классы в pug не забывайте обновлять имена классов в LESS файле чтобы стили применялись к блокам с данными классами.
2) В заголовке с классом `about-info__skills` переопределить отступ с margin: 15px 0px 15px 0px; на `margin: 30px 0px 15px 0px`
3) Удалить у блока класс `flex-position-text` т.к. вы его не используете.
4) Переименовать класс `list-specification` на `list-technology`, а элементам внутри данного блока установить класс `list-technology__text`. После того как переименуете класс задайте для него свойство `text-align: center;`, чтобы выровнять надписи расположенные слева от индикаторов. Также у данного класса изменить отступы : `margin-top: 35px;` и `margin-bottom: 65px;`
5) У параграфа с текстом `Которые использую в работе` удалить утилитарный класс `mb-10`.
6) Выровнять блок в котором находится заголовок с текстом `Технологии` и кнопка `редактировать` чтобы он отображался на странице как на макете.

2018-12-17 18:00 UTC, IvanPlastun requested changes
1) У заголовка с текстом `Что я умею` удалить свойство `display: block`
2) У блока с классом `list-technology` удалить класс `title-1`.
3) У блока с классом `list-technology` удалить свойство `text-align: center;` также у данного блока удалить класс `color-width`.
4) Элементам с классом `list-technology__text` установить следующие свойства `text-align:center`, `color: #fff;`, `font-size: 24px;`, `font-weight: 700;`.
5) К параграфу с классом `indicator-block__text` добавить утилитарные классы `mt-0` и `mb-0`
6)  Переделать блок с заголовком `Опыт работы` и кнопкой `Редактировать` c вот этого:
`.row
                .offset-md-3.col-md-3
                    span.workflow.title-1 Опыт работы
                .offset-md-4.col-md-2
                    +buttonSubmit('Редактировать', 'edit-button', 'edit')`
На вот это:
`.row
     .offset-md-3.col-md-9.exp-work.mb-25
              p.workflow.title-1.mt-0.mb-0 Опыт работы
              +buttonSubmit('Редактировать', 'edit-button', 'edit')`
В класс `.exp-work` добавить следующие свойства: `display: flex;
    justify-content: space-between;
    align-items: flex-start;`
7) Переделать блок с классом `.workflow-block` с вот этого:
`.workflow-block
		.workflow-block__date
			.workflow__date.mb-20 февраль 2017
			.workflow__date по настоящее время
		.workflow-info
			span.workflow-info__profile.title-4 Frontend разработчик, Вконтакте, mail.ru group
			p.workflow-info__text Работы в команде Вконтакте. Работал в команде над обновлением сервиса Музыка, работа над видео разделом. Создание видеолеера. Создание кроссбраузерных компонентов.  Работа над оптимизацией скорости загрузки медиа контента.`
`********************************************************************************************************`
На вот это:
`.workflow-block.mb-40
		.workflow-block__date.mb-15
			span февраль 2017  — по настоящее время
		.workflow-info
			h4.workflow-info__profile.title-4.mb-15.mt-0 Frontend разработчик, Вконтакте, mail.ru group
			p.workflow-info__text Работы в команде Вконтакте. Работал в команде над обновлением сервиса Музыка, работа над видео разделом. Создание видеолеера. Создание кроссбраузерных компонентов.  Работа над оптимизацией скорости загрузки медиа контента.`

Блоку с классом `workflow-block__date` добавить вот эти свойства: 
`font-family: 'Open Sans', sans-serif;  color: rgba(0, 0, 0, 0.502);  line-height: 1;`
Удалить класс `.workflow__date` и его селектор в less.

Параграфу с классом `.workflow-info__text` добавить следующие свойства: 
`font-family: @baseFont;  font-size: 16px;  font-weight: 400;  line-height: 1.5; margin: 0;`
`******************************************************************************************************`
8) У блока с классом `sectoin-workflow` переопределить утилитарные классы, установить `pt-80` и `pb-120`.

2018-12-18 08:02 UTC, IrinaVSerova commented
и снова исправила

2018-12-18 11:47 UTC, IvanPlastun requested changes
1) Заголовку с текстом `Разработчик интерфейсов, Яндекс` добавить утилитарный класс `mt-0` и для заголовка `Веб-разработчик, Cloud studio` сделать то же самое.
2) У третьего блока с классом `workflow-block` удалить утилитарный класс `mb-40` т.к. получается снизу отступ равен не 120px, а 40 + 120 = 160px, а у нас отступ должен быть `120px`;
3) У элементов с классом `.list-technology__text` удалить свойство `margin: 0;`
4) Изменить у блока с классом `section-indikators` утилитарный класс pt-80 на `pt-50`
5) После выполнения изменений не забывайте обновлять код страницы в документации внутри тега `pre`
6) В документации в блок `.section-ui` не нужно целиком вставлять код страницы для её визуального отображения. Сделайте вот так:
`block content
     .section-ui
          include ../about-me.pug
`

2018-12-18 16:08 UTC, IrinaVSerova commented
сделала

2018-12-18 19:47 UTC, IvanPlastun approved these changes
Все на данный момент все хорошо. Устраняйте конфликты и выполняйте слияние в develop. Также во время устранения конфликтов будьте внимательны, смотрите что необходимо оставить, а что удалить.

2018-12-19 02:55 UTC, merged